MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  NAME: 'se_resnet50'
  PRETRAIN_PATH: '/data/xiangan/pretrain_models/se_resnet50-ce0d4300.pth'
  METRIC_LOSS_TYPE: 'triplet_center'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'yes'

INPUT:
  SIZE_TRAIN: [384, 128]
  SIZE_TEST: [384, 128]
  # random horizontal flip
  PROB: 0.5
  PADDING: 10
  # random patch
  RANDOM_PATCH_PROB: 0.3
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, -0.224, -0.225]
DATASETS:
  NAMES: ('dukemtmc')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 24

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 80
  BASE_LR: 5e-3                                               #

  # center loss
  CENTER_LR: 0.5
  CENTER_LOSS_WEIGHT: 8e-5                                    #

  MARGIN: 1.5                                                 #

  # LR
  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 128

  STEPS: [50, 70]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 80                                       #
  LOG_PERIOD: 100
  EVAL_PERIOD: 10                                             #

TEST:
  IMS_PER_BATCH: 128
  RE_RANKING: 'no'
  WEIGHT: "path"
  FEAT_NORM: 'yes'

OUTPUT_DIR: ""


